module.exports = {
    /*
     * We have to specify the path to the configs for each sub-library
     * rather than the configs themselves, so that each sub-library's config
     * is able to pull in a large dependency graph without impacting
     * on other sub-libraries. For example, plugins for DotPHP may pull in
     * dependencies for talking to the host filesystem, which may make
     * little sense browser-side, so we wouldn't want to include them
     * in the bundle generated by a Webpack loader using PHPify.
     */
    'my_transpiler_lib': __dirname + '/config.transpiler',
};
